id: I587AE955
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:32:50+00:00'
last_modified: '2022-06-08T01:37:39.796400+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS56154
  title: ཆོས་ཀྱི་རྗེ་ཀརྨ་ཕྲིན་ལས་པའི་གསུང་འབུམ་ལས་རྡོ་རྗེའི་མགུར་གྱི་ཕྲེང་བ་དང་ཐུན་མོང་བའི་དྲིས་ལན་གྱི་ཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DD84:
      image_group_id: I1GS56157
      title: ''
      total_pages: 128
      order: 1
      base_file: DD84.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
