id: P004515
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1GS56154
  title: ཆོས་ཀྱི་རྗེ་ཀརྨ་ཕྲིན་ལས་པའི་གསུང་འབུམ་ལས་རྡོ་རྗེའི་མགུར་གྱི་ཕྲེང་བ་དང་ཐུན་མོང་བའི་དྲིས་ལན་གྱི་ཕྲེང་བ།
  author: ''
  volumes:
    ad700451ac614482b36c781c28592d28:
      image_group_id: I1GS56157
      title: ''
      volume_number: 1
      total_pages: 128
      base_file: v001.txt
